# ci
include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - lint
  - test
  - security
  - deploy

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

ruff:
  stage: lint
  before_script:
    - python3 --version
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - export UV_LINK_MODE="copy"
    - uv venv
    - uv pip install --upgrade pip
    - uv pip install ruff bandit detect-secrets pip-audit
    - source .venv/bin/activate
  script:
    - cd "$CI_PROJECT_DIR"
    - ruff check .
    - ruff format --check .

bandit:
  stage: security
  before_script:
    - python3 --version
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - export UV_LINK_MODE="copy"
    - uv venv
    - uv pip install --upgrade pip
    - uv pip install ruff bandit detect-secrets pip-audit
    - source .venv/bin/activate
  script:
    - cd "$CI_PROJECT_DIR"
    - bandit -r "$CI_PROJECT_DIR" -x "$CI_PROJECT_DIR/.venv,$CI_PROJECT_DIR/tests" -v -f html -o bandit-report.html
  artifacts:
    paths:
      - bandit-report.html
  allow_failure: true

detect_secrets:
  stage: security
  before_script:
    - python3 --version
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - export UV_LINK_MODE="copy"
    - uv venv
    - uv pip install --upgrade pip
    - uv pip install ruff bandit detect-secrets pip-audit
    - source .venv/bin/activate
  script:
    - cd "$CI_PROJECT_DIR"
    - detect-secrets scan --all-files --exclude-files '\.git/config' > .secrets.baseline

pip_audit:
  stage: security
  before_script:
    - python3 --version
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - export UV_LINK_MODE="copy"
    - uv venv
    - uv pip install --upgrade pip
    - uv pip install ruff bandit detect-secrets pip-audit
    - source .venv/bin/activate
  script:
    - cd "$CI_PROJECT_DIR"
    - pip-audit --format json -o pip-audit-report.json
  artifacts:
    paths:
      - pip-audit-report.json

trivy_fs_scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - cd "$CI_PROJECT_DIR"
    - trivy fs --exit-code 1 --severity HIGH,CRITICAL . -f json -o trivy-fs-report.json
  artifacts:
    paths:
      - trivy-fs-report.json
  allow_failure: false

trivy_python_image_scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL python:3.12-bookworm -f json -o trivy-image-report.json
  artifacts:
    paths:
      - trivy-image-report.json
  allow_failure: true

collect_reports:
  stage: deploy
  script:
    - mkdir -p public
    # Copy available reports (some may not exist due to allow_failure: true)
    - cp bandit-report.html public/ 2>/dev/null || echo "bandit-report.html not found"
    - cp pip-audit-report.json public/ 2>/dev/null || echo "pip-audit-report.json not found"
    - cp trivy-fs-report.json public/ 2>/dev/null || echo "trivy-fs-report.json not found"
    - cp trivy-image-report.json public/ 2>/dev/null || echo "trivy-image-report.json not found"
    # Convert pip-audit JSON to HTML (only if file exists)
    - if [ -f pip-audit-report.json ]; then python3 opnsense_mcp/tools/convert_pip_audit_to_html.py pip-audit-report.json public/pip-audit-report.html; else echo "pip-audit-report.json not found, skipping conversion"; fi
    # Convert Trivy JSONs to HTML (only if files exist)
    - if [ -f trivy-fs-report.json ]; then python3 opnsense_mcp/tools/convert_trivy_to_html.py trivy-fs-report.json public/trivy-fs-report.html; else echo "trivy-fs-report.json not found, skipping conversion"; fi
    - if [ -f trivy-image-report.json ]; then python3 opnsense_mcp/tools/convert_trivy_to_html.py trivy-image-report.json public/trivy-image-report.html; else echo "trivy-image-report.json not found, skipping conversion"; fi
    # Generate index.html with links to all files in public
    - |
      python3 -c "
      import os
      files = os.listdir('public')
      with open('public/index.html', 'w') as f:
          f.write('<html><head><title>Security Reports</title></head><body>')
          f.write('<h1>Security Reports</h1>')
          for file in files:
              if file != 'index.html':
                  f.write(f'<a href=\"{file}\">{file}</a><br>')
          f.write('</body></html>')
      "
  dependencies:
    - bandit
    - pip_audit
    - trivy_fs_scan
    - trivy_python_image_scan
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mkdir -p public
    # - echo "Publishing reports via GitLab Pages" > public.index.html
  artifacts:
    paths:
      - public
  only:
    - main
